/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmiyaSlider {
        "max": number;
        "min": number;
        "onChange": (value: number) => void;
        "progressBarBaseColor": string;
        "progressBarHeight": number;
        "progressBarLeftColor": string;
        "slideHandleRadius": number;
        "value": number;
    }
    interface EmiyaTeleport {
        "targetSelector"?: string;
    }
    interface EmiyaTooltip {
        "boundingElement"?: HTMLElement | undefined;
        "forceVisible"?: boolean;
    }
    interface EmiyaVerticalSlider {
        "max": number;
        "min": number;
        "onChange": (value: number) => void;
        "progressBarBaseColor": string;
        "progressBarLeftColor": string;
        "progressBarWidth": number;
        "slideHandleRadius": number;
        "value": number;
    }
    interface EmiyaVideo {
        "src"?: string;
    }
    interface EmiyaVideoProgressBar {
        "videoRef"?: HTMLVideoElement | undefined;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface VolumeController {
        "videoRef": HTMLVideoElement;
    }
}
export interface EmiyaTooltipCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmiyaTooltipElement;
}
export interface EmiyaVerticalSliderCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmiyaVerticalSliderElement;
}
export interface EmiyaVideoProgressBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLEmiyaVideoProgressBarElement;
}
declare global {
    interface HTMLEmiyaSliderElement extends Components.EmiyaSlider, HTMLStencilElement {
    }
    var HTMLEmiyaSliderElement: {
        prototype: HTMLEmiyaSliderElement;
        new (): HTMLEmiyaSliderElement;
    };
    interface HTMLEmiyaTeleportElement extends Components.EmiyaTeleport, HTMLStencilElement {
    }
    var HTMLEmiyaTeleportElement: {
        prototype: HTMLEmiyaTeleportElement;
        new (): HTMLEmiyaTeleportElement;
    };
    interface HTMLEmiyaTooltipElementEventMap {
        "visibilityChange": boolean;
    }
    interface HTMLEmiyaTooltipElement extends Components.EmiyaTooltip, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmiyaTooltipElementEventMap>(type: K, listener: (this: HTMLEmiyaTooltipElement, ev: EmiyaTooltipCustomEvent<HTMLEmiyaTooltipElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmiyaTooltipElementEventMap>(type: K, listener: (this: HTMLEmiyaTooltipElement, ev: EmiyaTooltipCustomEvent<HTMLEmiyaTooltipElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmiyaTooltipElement: {
        prototype: HTMLEmiyaTooltipElement;
        new (): HTMLEmiyaTooltipElement;
    };
    interface HTMLEmiyaVerticalSliderElementEventMap {
        "isDraggingChange": boolean;
    }
    interface HTMLEmiyaVerticalSliderElement extends Components.EmiyaVerticalSlider, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmiyaVerticalSliderElementEventMap>(type: K, listener: (this: HTMLEmiyaVerticalSliderElement, ev: EmiyaVerticalSliderCustomEvent<HTMLEmiyaVerticalSliderElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmiyaVerticalSliderElementEventMap>(type: K, listener: (this: HTMLEmiyaVerticalSliderElement, ev: EmiyaVerticalSliderCustomEvent<HTMLEmiyaVerticalSliderElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmiyaVerticalSliderElement: {
        prototype: HTMLEmiyaVerticalSliderElement;
        new (): HTMLEmiyaVerticalSliderElement;
    };
    interface HTMLEmiyaVideoElement extends Components.EmiyaVideo, HTMLStencilElement {
    }
    var HTMLEmiyaVideoElement: {
        prototype: HTMLEmiyaVideoElement;
        new (): HTMLEmiyaVideoElement;
    };
    interface HTMLEmiyaVideoProgressBarElementEventMap {
        "currentTimeChange": number;
        "durationChange": number;
    }
    interface HTMLEmiyaVideoProgressBarElement extends Components.EmiyaVideoProgressBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLEmiyaVideoProgressBarElementEventMap>(type: K, listener: (this: HTMLEmiyaVideoProgressBarElement, ev: EmiyaVideoProgressBarCustomEvent<HTMLEmiyaVideoProgressBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLEmiyaVideoProgressBarElementEventMap>(type: K, listener: (this: HTMLEmiyaVideoProgressBarElement, ev: EmiyaVideoProgressBarCustomEvent<HTMLEmiyaVideoProgressBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLEmiyaVideoProgressBarElement: {
        prototype: HTMLEmiyaVideoProgressBarElement;
        new (): HTMLEmiyaVideoProgressBarElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLVolumeControllerElement extends Components.VolumeController, HTMLStencilElement {
    }
    var HTMLVolumeControllerElement: {
        prototype: HTMLVolumeControllerElement;
        new (): HTMLVolumeControllerElement;
    };
    interface HTMLElementTagNameMap {
        "emiya-slider": HTMLEmiyaSliderElement;
        "emiya-teleport": HTMLEmiyaTeleportElement;
        "emiya-tooltip": HTMLEmiyaTooltipElement;
        "emiya-vertical-slider": HTMLEmiyaVerticalSliderElement;
        "emiya-video": HTMLEmiyaVideoElement;
        "emiya-video-progress-bar": HTMLEmiyaVideoProgressBarElement;
        "my-component": HTMLMyComponentElement;
        "volume-controller": HTMLVolumeControllerElement;
    }
}
declare namespace LocalJSX {
    interface EmiyaSlider {
        "max"?: number;
        "min"?: number;
        "onChange"?: (value: number) => void;
        "progressBarBaseColor"?: string;
        "progressBarHeight"?: number;
        "progressBarLeftColor"?: string;
        "slideHandleRadius"?: number;
        "value"?: number;
    }
    interface EmiyaTeleport {
        "targetSelector"?: string;
    }
    interface EmiyaTooltip {
        "boundingElement"?: HTMLElement | undefined;
        "forceVisible"?: boolean;
        "onVisibilityChange"?: (event: EmiyaTooltipCustomEvent<boolean>) => void;
    }
    interface EmiyaVerticalSlider {
        "max"?: number;
        "min"?: number;
        "onChange"?: (value: number) => void;
        "onIsDraggingChange"?: (event: EmiyaVerticalSliderCustomEvent<boolean>) => void;
        "progressBarBaseColor"?: string;
        "progressBarLeftColor"?: string;
        "progressBarWidth"?: number;
        "slideHandleRadius"?: number;
        "value"?: number;
    }
    interface EmiyaVideo {
        "src"?: string;
    }
    interface EmiyaVideoProgressBar {
        "onCurrentTimeChange"?: (event: EmiyaVideoProgressBarCustomEvent<number>) => void;
        "onDurationChange"?: (event: EmiyaVideoProgressBarCustomEvent<number>) => void;
        "videoRef"?: HTMLVideoElement | undefined;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface VolumeController {
        "videoRef"?: HTMLVideoElement;
    }
    interface IntrinsicElements {
        "emiya-slider": EmiyaSlider;
        "emiya-teleport": EmiyaTeleport;
        "emiya-tooltip": EmiyaTooltip;
        "emiya-vertical-slider": EmiyaVerticalSlider;
        "emiya-video": EmiyaVideo;
        "emiya-video-progress-bar": EmiyaVideoProgressBar;
        "my-component": MyComponent;
        "volume-controller": VolumeController;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emiya-slider": LocalJSX.EmiyaSlider & JSXBase.HTMLAttributes<HTMLEmiyaSliderElement>;
            "emiya-teleport": LocalJSX.EmiyaTeleport & JSXBase.HTMLAttributes<HTMLEmiyaTeleportElement>;
            "emiya-tooltip": LocalJSX.EmiyaTooltip & JSXBase.HTMLAttributes<HTMLEmiyaTooltipElement>;
            "emiya-vertical-slider": LocalJSX.EmiyaVerticalSlider & JSXBase.HTMLAttributes<HTMLEmiyaVerticalSliderElement>;
            "emiya-video": LocalJSX.EmiyaVideo & JSXBase.HTMLAttributes<HTMLEmiyaVideoElement>;
            "emiya-video-progress-bar": LocalJSX.EmiyaVideoProgressBar & JSXBase.HTMLAttributes<HTMLEmiyaVideoProgressBarElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "volume-controller": LocalJSX.VolumeController & JSXBase.HTMLAttributes<HTMLVolumeControllerElement>;
        }
    }
}
