/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmiyaSlider {
        "max": number;
        "min": number;
        "value": number;
    }
    interface EmiyaTeleport {
        "targetSelector"?: string;
    }
    interface EmiyaVideo {
        "src"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLEmiyaSliderElement extends Components.EmiyaSlider, HTMLStencilElement {
    }
    var HTMLEmiyaSliderElement: {
        prototype: HTMLEmiyaSliderElement;
        new (): HTMLEmiyaSliderElement;
    };
    interface HTMLEmiyaTeleportElement extends Components.EmiyaTeleport, HTMLStencilElement {
    }
    var HTMLEmiyaTeleportElement: {
        prototype: HTMLEmiyaTeleportElement;
        new (): HTMLEmiyaTeleportElement;
    };
    interface HTMLEmiyaVideoElement extends Components.EmiyaVideo, HTMLStencilElement {
    }
    var HTMLEmiyaVideoElement: {
        prototype: HTMLEmiyaVideoElement;
        new (): HTMLEmiyaVideoElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "emiya-slider": HTMLEmiyaSliderElement;
        "emiya-teleport": HTMLEmiyaTeleportElement;
        "emiya-video": HTMLEmiyaVideoElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface EmiyaSlider {
        "max"?: number;
        "min"?: number;
        "value"?: number;
    }
    interface EmiyaTeleport {
        "targetSelector"?: string;
    }
    interface EmiyaVideo {
        "src"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "emiya-slider": EmiyaSlider;
        "emiya-teleport": EmiyaTeleport;
        "emiya-video": EmiyaVideo;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "emiya-slider": LocalJSX.EmiyaSlider & JSXBase.HTMLAttributes<HTMLEmiyaSliderElement>;
            "emiya-teleport": LocalJSX.EmiyaTeleport & JSXBase.HTMLAttributes<HTMLEmiyaTeleportElement>;
            "emiya-video": LocalJSX.EmiyaVideo & JSXBase.HTMLAttributes<HTMLEmiyaVideoElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
